# Generated by Django 4.1.3 on 2023-01-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_dummypost"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostModelLEvel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("body", models.TextField()),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "permissions": [
                    (
                        "set_published_status",
                        "Can set the status of the post to either publish or not",
                    )
                ],
            },
        ),
    ]
