# Generated by Django 4.1.3 on 2023-01-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_munimodel_disastermodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disastermodel",
            options={
                "permissions": (("update_isclosed", "Update the disaster status"),)
            },
        ),
        migrations.AddField(
            model_name="disastermodel",
            name="isclosed",
            field=models.BooleanField(default=False),
        ),
    ]
