# Generated by Django 4.1.3 on 2023-01-11 04:15

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_student_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("userapp.user",),
            managers=[
                ("student", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
